language: node_js

sudo: true

node_js:
  - 8
  - 10

before_install:
  - ssh-keygen -t rsa -N "" -f ${TRAVIS_HOME}/.ssh/id_rsa
  - cat ${TRAVIS_HOME}/.ssh/id_rsa.pub | tee -a ${TRAVIS_HOME}/.ssh/authorized_keys
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

script:
  - yarn ci

notifications:
  email: false

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

addons:
  ssh_known_hosts:
    - 127.0.0.1
    - 0.0.0.0
    - localhost
