language: node_js

node_js:
  - 8
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.4
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - chmod 700 ssh && chmod 644 ssh/id_rsa.pub && chmod 600 ssh/id_rsa
  - yarn ci

notifications:
  email: false

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

addons:
  ssh_known_hosts: test.shipitjs.com
